In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/marketing-strategy-personalised-offer/sample.csv
/kaggle/input/marketing-strategy-personalised-offer/train_data.csv
/kaggle/input/marketing-strategy-personalised-offer/test_data.csv


In [2]:
# train_data=pd.read_csv('../input/marketing-strategy-personalised-offer/train_data.csv')
# test_data=pd.read_csv('/kaggle/input/marketing-strategy-personalised-offer/test_data.csv')
# prediction=test_data
# # Select only required coulums
# submission=pd.DataFrame(columns=['id','Offer Accepted'])

# submission['id']=[i for i in range(len(prediction))]

# # Mark all as Yes , just for submission
# submission['Offer Accepted']=['Yes' for i in range(len(prediction))]

# # Export it as an csv
# submission.to_csv('submission.csv',index=False)

In [3]:
train_data=pd.read_csv('/kaggle/input/marketing-strategy-personalised-offer/train_data.csv')
testdata=pd.read_csv('../input/marketing-strategy-personalised-offer/test_data.csv')

In [4]:

train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12379 entries, 0 to 12378
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype 
---  ------                                --------------  ----- 
 0   offer expiration                      12379 non-null  object
 1   income_range                          12379 non-null  object
 2   no_visited_Cold drinks                12181 non-null  object
 3   travelled_more_than_15mins_for_offer  12379 non-null  int64 
 4   Restaur_spend_less_than20             12258 non-null  object
 5   Marital Status                        12379 non-null  object
 6   restaurant type                       12379 non-null  object
 7   age                                   12379 non-null  object
 8   Prefer western over chinese           12379 non-null  int64 
 9   travelled_more_than_25mins_for_offer  12379 non-null  int64 
 10  travelled_more_than_5mins_for_offer   12379 non-null  int64 
 11  no_visited_bars             

In [5]:
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5305 entries, 0 to 5304
Data columns (total 30 columns):
 #   Column                                Non-Null Count  Dtype 
---  ------                                --------------  ----- 
 0   offer expiration                      5305 non-null   object
 1   income_range                          5305 non-null   object
 2   no_visited_Cold drinks                5215 non-null   object
 3   travelled_more_than_15mins_for_offer  5305 non-null   int64 
 4   Restaur_spend_less_than20             5244 non-null   object
 5   Marital Status                        5305 non-null   object
 6   restaurant type                       5305 non-null   object
 7   age                                   5305 non-null   object
 8   Prefer western over chinese           5305 non-null   int64 
 9   travelled_more_than_25mins_for_offer  5305 non-null   int64 
 10  travelled_more_than_5mins_for_offer   5305 non-null   int64 
 11  no_visited_bars               

In [6]:
train_data.columns

Index(['offer expiration', 'income_range', 'no_visited_Cold drinks',
       'travelled_more_than_15mins_for_offer', 'Restaur_spend_less_than20',
       'Marital Status', 'restaurant type', 'age',
       'Prefer western over chinese', 'travelled_more_than_25mins_for_offer',
       'travelled_more_than_5mins_for_offer', 'no_visited_bars', 'gender',
       'car', 'restuarant_same_direction_house', 'Cooks regularly',
       'Customer type', 'Qualification', 'is foodie', 'no_Take-aways',
       'Job/Job Industry', 'restuarant_opposite_direction_house',
       'has Children', 'visit restaurant with rating (avg)', 'temperature',
       'Restaur_spend_greater_than20', 'Travel Time', 'Climate',
       'drop location', 'Prefer home food', 'Offer Accepted'],
      dtype='object')

In [7]:
testdata.columns

Index(['offer expiration', 'income_range', 'no_visited_Cold drinks',
       'travelled_more_than_15mins_for_offer', 'Restaur_spend_less_than20',
       'Marital Status', 'restaurant type', 'age',
       'Prefer western over chinese', 'travelled_more_than_25mins_for_offer',
       'travelled_more_than_5mins_for_offer', 'no_visited_bars', 'gender',
       'car', 'restuarant_same_direction_house', 'Cooks regularly',
       'Customer type', 'Qualification', 'is foodie', 'no_Take-aways',
       'Job/Job Industry', 'restuarant_opposite_direction_house',
       'has Children', 'visit restaurant with rating (avg)', 'temperature',
       'Restaur_spend_greater_than20', 'Travel Time', 'Climate',
       'drop location', 'Prefer home food'],
      dtype='object')

In [8]:
train_data['offer expiration'].unique()
train_data.shape

(12379, 31)

In [9]:
testdata.shape

(5305, 30)

In [10]:
train_data=train_data.replace(to_replace='2days',value=48)
train_data=train_data.replace(to_replace='10hours',value=10)
train_data['offer expiration'].unique()

array([48, 10])

In [11]:
testdata=testdata.replace(to_replace='2days',value=48)
testdata=testdata.replace(to_replace='10hours',value=10)
testdata['offer expiration'].unique()

array([48, 10])

In [12]:
train_data['income_range'].unique()

array(['₹100000 or More', '₹87500 - ₹99999', '₹37500 - ₹49999',
       'Less than ₹12500', '₹50000 - ₹62499', '₹12500 - ₹24999',
       '₹75000 - ₹87499', '₹25000 - ₹37499', '₹62500 - ₹74999'],
      dtype=object)

In [13]:
# def transf1(data):
#     return data.split(' - ')
# train_data['income_range']=train_data['income_range'].apply(transf1)
# train_data['income_range']=pd.DataFrame(train_data['income_range'])
# def transf2(data):
#     if data[0]!='₹100000 or More':
#         for i in range(len(data)):
#             data[i]=int(data[i].split('₹')[1])
#         data=sum(data)
#         return data/2
#     else:
#         data=100000
#         return data
    
    
    
# train_data['income_range']=train_data['income_range'].apply(transf2)
# train_data['income_range']=pd.DataFrame(train_data['income_range'])
# train_data.head()

In [14]:
# train_data['no_visited_Cold drinks'].unique()
# train_data['no_visited_Cold drinks']=train_data['no_visited_Cold drinks'].replace(to_replace='4~8',value=6)
# train_data['no_visited_Cold drinks']=train_data['no_visited_Cold drinks'].replace(to_replace='less1',value=1)
# train_data['no_visited_Cold drinks']=train_data['no_visited_Cold drinks'].replace(to_replace='never',value=0)
# train_data['no_visited_Cold drinks']=train_data['no_visited_Cold drinks'].replace(to_replace='1~3',value=2)
# train_data['no_visited_Cold drinks']=train_data['no_visited_Cold drinks'].replace(to_replace='gt8',value=8)
# train_data['no_visited_Cold drinks'].unique()

In [15]:
train_data.head()

offer expiration     income_range no_visited_Cold drinks  \
0                48  ₹100000 or More                    4~8   
1                48  ₹87500 - ₹99999                    4~8   
2                48  ₹87500 - ₹99999                  less1   
3                10  ₹37500 - ₹49999                  less1   
4                48  ₹100000 or More                  never   

   travelled_more_than_15mins_for_offer Restaur_spend_less_than20  \
0                                     1                     less1   
1                                     0                       4~8   
2                                     1                       1~3   
3                                     0                       1~3   
4                                     1                       1~3   

    Marital Status       restaurant type     age  Prefer western over chinese  \
0  Married partner     4 star restaurant      36                            0   
1  Married partner  Take-away restaurant  50plus                            0   
2           Single           Cold drinks      26                            1   
3           Single  Take-away restaurant      46                            1   
4           Single     4 star restaurant      21                            0   

   travelled_more_than_25mins_for_offer  ...  \
0                                     0  ...   
1                                     0  ...   
2                                     0  ...   
3                                     0  ...   
4                                     1  ...   

   restuarant_opposite_direction_house has Children  \
0                                    0            0   
1                                    0            1   
2                                    1            1   
3                                    0            1   
4                                    1            0   

  visit restaurant with rating (avg) temperature  \
0                                  4          67   
1                                  3          89   
2                                  4          67   
3                                  3          89   
4                                  3          40   

   Restaur_spend_greater_than20  Travel Time Climate drop location  \
0                         less1           22  Spring    Location B   
1                           1~3           18  Summer    Location B   
2                         less1            7  Winter    Location A   
3                           1~3            7  Summer    Location C   
4                         less1            7  Summer    Location C   

   Prefer home food Offer Accepted  
0                 0             No  
1                 0            Yes  
2                 1            Yes  
3                 0             No  
4                 0             No  

[5 rows x 31 columns]

In [16]:
train_data['no_visited_Cold drinks'].unique()

array(['4~8', 'less1', 'never', '1~3', 'gt8', nan], dtype=object)

In [17]:
train_data['travelled_more_than_15mins_for_offer'].unique()

array([1, 0])

In [18]:
train_data.head()

offer expiration     income_range no_visited_Cold drinks  \
0                48  ₹100000 or More                    4~8   
1                48  ₹87500 - ₹99999                    4~8   
2                48  ₹87500 - ₹99999                  less1   
3                10  ₹37500 - ₹49999                  less1   
4                48  ₹100000 or More                  never   

   travelled_more_than_15mins_for_offer Restaur_spend_less_than20  \
0                                     1                     less1   
1                                     0                       4~8   
2                                     1                       1~3   
3                                     0                       1~3   
4                                     1                       1~3   

    Marital Status       restaurant type     age  Prefer western over chinese  \
0  Married partner     4 star restaurant      36                            0   
1  Married partner  Take-away restaurant  50plus                            0   
2           Single           Cold drinks      26                            1   
3           Single  Take-away restaurant      46                            1   
4           Single     4 star restaurant      21                            0   

   travelled_more_than_25mins_for_offer  ...  \
0                                     0  ...   
1                                     0  ...   
2                                     0  ...   
3                                     0  ...   
4                                     1  ...   

   restuarant_opposite_direction_house has Children  \
0                                    0            0   
1                                    0            1   
2                                    1            1   
3                                    0            1   
4                                    1            0   

  visit restaurant with rating (avg) temperature  \
0                                  4          67   
1                                  3          89   
2                                  4          67   
3                                  3          89   
4                                  3          40   

   Restaur_spend_greater_than20  Travel Time Climate drop location  \
0                         less1           22  Spring    Location B   
1                           1~3           18  Summer    Location B   
2                         less1            7  Winter    Location A   
3                           1~3            7  Summer    Location C   
4                         less1            7  Summer    Location C   

   Prefer home food Offer Accepted  
0                 0             No  
1                 0            Yes  
2                 1            Yes  
3                 0             No  
4                 0             No  

[5 rows x 31 columns]

In [19]:
# train_data['Restaur_spend_less_than20'].unique()
# train_data['Restaur_spend_less_than20']=train_data['Restaur_spend_less_than20'].replace(to_replace='4~8',value=6)
# train_data['Restaur_spend_less_than20']=train_data['Restaur_spend_less_than20'].replace(to_replace='less1',value=1)
# train_data['Restaur_spend_less_than20']=train_data['Restaur_spend_less_than20'].replace(to_replace='never',value=0)
# train_data['Restaur_spend_less_than20']=train_data['Restaur_spend_less_than20'].replace(to_replace='1~3',value=2)
# train_data['Restaur_spend_less_than20']=train_data['Restaur_spend_less_than20'].replace(to_replace='gt8',value=8)
# train_data['Restaur_spend_less_than20'].unique()

In [20]:
train_data['Marital Status'].unique()

array(['Married partner', 'Single', 'Divorced', 'Unmarried partner',
       'Widowed'], dtype=object)

In [21]:
train_data['restaurant type'].unique()

array(['4 star restaurant', 'Take-away restaurant', 'Cold drinks',
       'Restaurant with pub', '2 star restaurant'], dtype=object)

In [22]:
# train_data['age'].unique()
# train_data['age']=train_data['age'].replace(to_replace='50plus',value=55)
# train_data['age']=train_data['age'].replace(to_replace='below21',value=21)
# train_data['age']=pd.to_numeric(train_data['age'])
# train_data['age'].unique()

In [23]:
train_data['Prefer western over chinese'].unique()

array([0, 1])

In [24]:
train_data['travelled_more_than_25mins_for_offer'].unique()

array([0, 1])

In [25]:
train_data['Job/Job Industry'].unique()

array(['Unemployed', 'Arts Design Entertainment Sports & Media',
       'Sales & Related', 'Student', 'Business & Financial',
       'Computer & Mathematical', 'Office & Administrative Support',
       'Management', 'Healthcare Support', 'Life Physical Social Science',
       'Installation Maintenance & Repair', 'Legal',
       'Community & Social Services', 'Education&Training&Library',
       'Construction & Extraction',
       'Healthcare Practitioners & Technical',
       'Transportation & Material Moving', 'Retired',
       'Architecture & Engineering', 'Production Occupations',
       'Farming Fishing & Forestry', 'Protective Service',
       'Personal Care & Service', 'Food Preparation & Serving Related',
       'Building & Grounds Cleaning & Maintenance'], dtype=object)

In [26]:
train_data['restuarant_opposite_direction_house'].unique()

array([0, 1])

In [27]:
train_data['has Children'].unique()


array([0, 1])

In [28]:
train_data['visit restaurant with rating (avg)'].unique()

array([4, 3, 0, 1, 2])

In [29]:
train_data['temperature'].unique()


array([67, 89, 40])

In [30]:
# train_data['Restaur_spend_greater_than20'].unique()
# train_data['Restaur_spend_greater_than20']=train_data['Restaur_spend_greater_than20'].replace(to_replace='4~8',value=6)
# train_data['Restaur_spend_greater_than20']=train_data['Restaur_spend_greater_than20'].replace(to_replace='less1',value=1)
# train_data['Restaur_spend_greater_than20']=train_data['Restaur_spend_greater_than20'].replace(to_replace='never',value=0)
# train_data['Restaur_spend_greater_than20']=train_data['Restaur_spend_greater_than20'].replace(to_replace='1~3',value=2)
# train_data['Restaur_spend_greater_than20']=train_data['Restaur_spend_greater_than20'].replace(to_replace='gt8',value=8)
# train_data['Restaur_spend_greater_than20'].unique()

In [31]:
train_data['Travel Time'].unique()

array([22, 18,  7, 10, 14])

In [32]:
train_data['Climate'].unique()

array(['Spring', 'Summer', 'Winter'], dtype=object)

In [33]:
train_data['drop location'].unique()

array(['Location B', 'Location A', 'Location C'], dtype=object)

In [34]:
train_data['Prefer home food'].unique()

array([0, 1])

In [35]:
target=train_data['Offer Accepted']

In [36]:
target.head()

0     No
1    Yes
2    Yes
3     No
4     No
Name: Offer Accepted, dtype: object

In [37]:
# colsame=['no_visited_Cold drinks','car','Restaur_spend_less_than20','no_Take-aways','Restaur_spend_greater_than20','no_visited_bars']
obj_colmn=[]
for i in train_data.columns:
    if train_data[i].dtype=='object' and i!='Offer Accepted':
        obj_colmn.append(i)
newlist=obj_colmn
newlist=list(set(newlist))
train_data=train_data.drop('Offer Accepted',axis=1)
newlist

['Customer type',
 'Job/Job Industry',
 'no_visited_bars',
 'no_Take-aways',
 'restaurant type',
 'age',
 'no_visited_Cold drinks',
 'Qualification',
 'Restaur_spend_greater_than20',
 'Climate',
 'income_range',
 'drop location',
 'Restaur_spend_less_than20',
 'car',
 'Marital Status',
 'gender']

In [38]:
len(newlist)

16

In [39]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
# transformations for training data
si=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
train_imputed=si.fit_transform(train_data)
train_imputed=pd.DataFrame(train_imputed,columns=train_data.columns)
ctf=ColumnTransformer([('ohe',OneHotEncoder(sparse=False),newlist)],remainder='passthrough')
train_tf=ctf.fit_transform(train_imputed)
newfeatures=ctf.get_feature_names()
train_tf=pd.DataFrame(train_tf,columns=newfeatures)
# train_tf.info()
# ----------------------------------------------------------------------------------------------------------
# transformations for test data
si2=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
test_imputed=si2.fit_transform(testdata)
test_imputed=pd.DataFrame(test_imputed,columns=testdata.columns)
ctf=ColumnTransformer([('ohe',OneHotEncoder(sparse=False),newlist)],remainder='passthrough')
test_tf=ctf.fit_transform(testdata)
newfeatures=ctf.get_feature_names()
test_tf=pd.DataFrame(test_tf,columns=newfeatures)
# test_tf.info()
# test_tf.head()
# train_tf=ct.fit_transform(train_data)
# ct.ohe.categories_

/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [40]:
train_tf.head()

ohe__x0_Individual ohe__x0_With Colleagues ohe__x0_With Family  \
0                1.0                     0.0                 0.0   
1                1.0                     0.0                 0.0   
2                1.0                     0.0                 0.0   
3                1.0                     0.0                 0.0   
4                1.0                     0.0                 0.0   

  ohe__x0_With Kids ohe__x1_Architecture & Engineering  \
0               0.0                                0.0   
1               0.0                                0.0   
2               0.0                                0.0   
3               0.0                                0.0   
4               0.0                                0.0   

  ohe__x1_Arts Design Entertainment Sports & Media  \
0                                              0.0   
1                                              0.0   
2                                              1.0   
3                                              0.0   
4                                              0.0   

  ohe__x1_Building & Grounds Cleaning & Maintenance  \
0                                               0.0   
1                                               0.0   
2                                               0.0   
3                                               0.0   
4                                               0.0   

  ohe__x1_Business & Financial ohe__x1_Community & Social Services  \
0                          0.0                                 0.0   
1                          0.0                                 0.0   
2                          0.0                                 0.0   
3                          0.0                                 0.0   
4                          0.0                                 0.0   

  ohe__x1_Computer & Mathematical  ... travelled_more_than_5mins_for_offer  \
0                             0.0  ...                                   1   
1                             0.0  ...                                   1   
2                             0.0  ...                                   1   
3                             0.0  ...                                   1   
4                             0.0  ...                                   1   

  restuarant_same_direction_house Cooks regularly is foodie  \
0                               0               1         0   
1                               1               1         0   
2                               1               0         1   
3                               1               0         1   
4                               0               0         1   

  restuarant_opposite_direction_house has Children  \
0                                   0            0   
1                                   0            1   
2                                   1            1   
3                                   0            1   
4                                   1            0   

  visit restaurant with rating (avg) temperature Travel Time Prefer home food  
0                                  4          67          22                0  
1                                  3          89          18                0  
2                                  4          67           7                1  
3                                  3          89           7                0  
4                                  3          40           7                0  

[5 rows x 114 columns]

In [41]:
test_tf.head()

ohe__x0_Individual  ohe__x0_With Colleagues  ohe__x0_With Family  \
0                 1.0                      0.0                  0.0   
1                 1.0                      0.0                  0.0   
2                 1.0                      0.0                  0.0   
3                 1.0                      0.0                  0.0   
4                 0.0                      0.0                  1.0   

   ohe__x0_With Kids  ohe__x1_Architecture & Engineering  \
0                0.0                                 0.0   
1                0.0                                 0.0   
2                0.0                                 0.0   
3                0.0                                 0.0   
4                0.0                                 0.0   

   ohe__x1_Arts Design Entertainment Sports & Media  \
0                                               0.0   
1                                               0.0   
2                                               0.0   
3                                               0.0   
4                                               0.0   

   ohe__x1_Building & Grounds Cleaning & Maintenance  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   

   ohe__x1_Business & Financial  ohe__x1_Community & Social Services  \
0                           0.0                                  0.0   
1                           0.0                                  0.0   
2                           0.0                                  0.0   
3                           0.0                                  0.0   
4                           0.0                                  0.0   

   ohe__x1_Computer & Mathematical  ...  travelled_more_than_5mins_for_offer  \
0                              0.0  ...                                  1.0   
1                              1.0  ...                                  1.0   
2                              0.0  ...                                  1.0   
3                              0.0  ...                                  1.0   
4                              0.0  ...                                  1.0   

   restuarant_same_direction_house  Cooks regularly  is foodie  \
0                              0.0              0.0        0.0   
1                              0.0              0.0        1.0   
2                              0.0              1.0        0.0   
3                              0.0              0.0        1.0   
4                              1.0              0.0        1.0   

   restuarant_opposite_direction_house  has Children  \
0                                  1.0           1.0   
1                                  1.0           1.0   
2                                  1.0           0.0   
3                                  1.0           1.0   
4                                  0.0           0.0   

   visit restaurant with rating (avg)  temperature  Travel Time  \
0                                 4.0         89.0          7.0   
1                                 0.0         67.0         18.0   
2                                 4.0         67.0          7.0   
3                                 0.0         40.0         18.0   
4                                 0.0         89.0         18.0   

   Prefer home food  
0               0.0  
1               1.0  
2               0.0  
3               1.0  
4               1.0  

[5 rows x 120 columns]

In [42]:
l1=test_tf.columns
l2=train_tf.columns
test_tf=test_tf.drop([val for val in test_tf.columns if val not in train_tf],axis=1)
print("no of features in train data: ",train_tf.shape[1])
print("no of features in test data: ",test_tf.shape[1])

no of features in train data:  114
no of features in test data:  114


In [43]:
target=target.replace('No',0)
target=target.replace('Yes',1)

In [44]:
train_tf.head()

ohe__x0_Individual ohe__x0_With Colleagues ohe__x0_With Family  \
0                1.0                     0.0                 0.0   
1                1.0                     0.0                 0.0   
2                1.0                     0.0                 0.0   
3                1.0                     0.0                 0.0   
4                1.0                     0.0                 0.0   

  ohe__x0_With Kids ohe__x1_Architecture & Engineering  \
0               0.0                                0.0   
1               0.0                                0.0   
2               0.0                                0.0   
3               0.0                                0.0   
4               0.0                                0.0   

  ohe__x1_Arts Design Entertainment Sports & Media  \
0                                              0.0   
1                                              0.0   
2                                              1.0   
3                                              0.0   
4                                              0.0   

  ohe__x1_Building & Grounds Cleaning & Maintenance  \
0                                               0.0   
1                                               0.0   
2                                               0.0   
3                                               0.0   
4                                               0.0   

  ohe__x1_Business & Financial ohe__x1_Community & Social Services  \
0                          0.0                                 0.0   
1                          0.0                                 0.0   
2                          0.0                                 0.0   
3                          0.0                                 0.0   
4                          0.0                                 0.0   

  ohe__x1_Computer & Mathematical  ... travelled_more_than_5mins_for_offer  \
0                             0.0  ...                                   1   
1                             0.0  ...                                   1   
2                             0.0  ...                                   1   
3                             0.0  ...                                   1   
4                             0.0  ...                                   1   

  restuarant_same_direction_house Cooks regularly is foodie  \
0                               0               1         0   
1                               1               1         0   
2                               1               0         1   
3                               1               0         1   
4                               0               0         1   

  restuarant_opposite_direction_house has Children  \
0                                   0            0   
1                                   0            1   
2                                   1            1   
3                                   0            1   
4                                   1            0   

  visit restaurant with rating (avg) temperature Travel Time Prefer home food  
0                                  4          67          22                0  
1                                  3          89          18                0  
2                                  4          67           7                1  
3                                  3          89           7                0  
4                                  3          40           7                0  

[5 rows x 114 columns]

RandomForestClassifier

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
param_grid={
    'n_estimators':[100,150,200],
    'max_depth':np.arange(1,10),
#     'learning_rate':np.linspace(0.001,0.005,5)
}
clf=GridSearchCV(RandomForestClassifier(warm_start=True,criterion='entropy',bootstrap=False,random_state=42),param_grid,scoring='f1',refit=True,cv=5,verbose=3,return_train_score=True,error_score='raise')
clf.fit(train_tf,target)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 1/5] END max_depth=1, n_estimators=100;, score=(train=0.722, test=0.722) total time=   0.5s
[CV 2/5] END max_depth=1, n_estimators=100;, score=(train=0.722, test=0.722) total time=   0.5s
[CV 3/5] END max_depth=1, n_estimators=100;, score=(train=0.722, test=0.722) total time=   0.5s
[CV 4/5] END max_depth=1, n_estimators=100;, score=(train=0.722, test=0.722) total time=   0.5s
[CV 5/5] END max_depth=1, n_estimators=100;, score=(train=0.722, test=0.722) total time=   0.5s
[CV 1/5] END max_depth=1, n_estimators=150;, score=(train=0.722, test=0.722) total time=   0.6s
[CV 2/5] END max_depth=1, n_estimators=150;, score=(train=0.722, test=0.722) total time=   0.6s
[CV 3/5] END max_depth=1, n_estimators=150;, score=(train=0.722, test=0.722) total time=   0.6s
[CV 4/5] END max_depth=1, n_estimators=150;, score=(train=0.722, test=0.722) total time=   0.6s
[CV 5/5] END max_depth=1, n_estimators=150;, score=(train=0.722, test=0.72

GridSearchCV(cv=5, error_score='raise',
             estimator=RandomForestClassifier(bootstrap=False,
                                              criterion='entropy',
                                              random_state=42,
                                              warm_start=True),
             param_grid={'max_depth': array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
                         'n_estimators': [100, 150, 200]},
             return_train_score=True, scoring='f1', verbose=3)

In [46]:
clf.best_score_
# clf.best_params_

0.7312751939794383

In [47]:
ypred=clf.predict(test_tf)
# ypred=pd.DataFrame(ypred)
# ypred=ypred.replace(0,'No')
# ypred=ypred.replace(1,'Yes')
# ypred.head()

In [48]:
from sklearn.metrics import f1_score

In [49]:
# Select only required coulums
submission=pd.DataFrame(columns=['id','Offer Accepted'])

submission['id']=[i for i in range(len(ypred))]

# Mark all as Yes , just for submission
submission['Offer Accepted']=ypred

# Export it as an csv
submission.to_csv('submission.csv',index=False)

In [50]:
submission

id  Offer Accepted
0        0               1
1        1               1
2        2               0
3        3               0
4        4               1
...    ...             ...
5300  5300               1
5301  5301               1
5302  5302               1
5303  5303               1
5304  5304               1

[5305 rows x 2 columns]